VERBOSE=1 DEFAULT_NETWORK_INTERFACE="enp1s0:1" FORCE_MXSERVER_IP="192.168.18.21" FORCE_CONQUEROR_IP=${FORCE_MXSERVER_IP} FAKE_REBOOT=1 SPLASHSCREEN_NW=/home/ale/buttami /opt/qubicaamf/scripts/start_whole_system.sh

