#!/bin/bash

chown ale:ale /home/ale/ --recursive

if [ \( -L "/usr/bin/qservice" \) ]
then
    rm /usr/bin/qservice
fi
ln -s /opt/qubicaamf/bin/qservice /usr/bin/qservice
sudo cp /home/ale/.config/conf_cache/failsafe.conf /etc/init/failsafe.conf
sudo cp /home/ale/.config/conf_cache/xorg.conf /etc/X11/xorg.conf

