#!/bin/bash
MY_TAG=nReboot
HUB_BIN="/matrix/bin/hub.bin"
SCRIPT_FOLDER="/opt/qubicaamf/scripts"
IP=$(ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')
MIONIBBLE=$(x=$(ifconfig eth0) && x=${x#*inet addr:} && echo ${x%% *} | awk 'BEGIN {FS="."} {print $4}')
[[ $MIONIBBLE -ge 101 && $MIONIBBLE -le 199 ]] && IS_SCORE=1

sync
if [ ${IS_SCORE:-0} -eq 1 ]
then
  HUB_IP=$(echo $IP | awk 'BEGIN {FS="."} {printf $1"."$2"."$3+1"."$4}')
  logger -s -t ${MY_TAG} I am score, tring to reboot hub ${HUB_IP}
  logger -s -t ${MY_TAG} Trying to stop whole system
  if [ -d ${SCRIPT_FOLDER} ]
  then
    ${SCRIPT_FOLDER}/stop_whole_system.sh
    sleep 10
  else
    logger -s -t ${MY_TAG} Script folder ${SCRIPT_FOLDER} does not exist
  fi

  sync

  [ ! -f ${HUB_BIN} ]  && logger -s -t ${MY_TAG} No file ${HUB_BIN}
  curl --upload-file ${HUB_BIN} tftp://${HUB_IP}:/r00000004 &
  sleepVal=7
  indiceSleep=1
  while [ $indiceSleep -le $sleepVal ]
  do
    logger -s -t ${MY_TAG} "Sleeping 1 second ( $indiceSleep/$sleepVal )"
    sleep 1
    let indiceSleep="$indiceSleep + 1"
  done
  sudo shutdown -H now -t 2
else
  logger -s -t ${MY_TAG} I am mms, rebooting
  sudo reboot
  sleep 10
  sudo reboot -f
fi
