#!/bin/bash

WIDTH_SX=1280
HEIGHT_SX=720
LEFT_SX=0
TOP_SX=0
WIDTH_DX=1280
HEIGHT_DX=720
LEFT_DX=0
TOP_DX=0

VIEWPORT_CONFIG=/opt/qubicaamf/monitor/transform

VERBOSE=${VERBOSE:-0}
[ $VERBOSE -ne 0 ] && set -x

log()
{
    logger -s -t "$(basename $0)" "$@"
}

check_params()
{
	[ $# -ne 2 ] && { echo "Wrong number of parameters" | ${TEE}; exit 1; }
	[[ "${1^^}" != "SX" && "${1^^}" != "DX" ]] && { echo "Parameter $1 is not valid" | ${TEE}; exit 1; }
	expr $2 + 1 &>/dev/null
	[ $? -ne 0 ] && { echo "Second parameter is not a number" | ${TEE}; exit 1;}
	[[ $2 -lt 0 || $2 -gt 200 ]] && { log "Second parameter must be in range 0 - 200";exit 1; }
	SIDE=${1^^}
	CONFIG_FILE=${VIEWPORT_CONFIG}/${SIDE}
	HORIZ_OFFSET=$2
	log "[${SIDE}] Using horizontal_offset ${HORIZ_OFFSET}"
}

create_default_viewport()
{
	log "[${SIDE}] create default viewport config"

	(
		echo "1,0,0,0,1,0,0,0,1"
  	echo "1280 720"
	) > ${CONFIG_FILE}
}

reset_mms()
{
	wget -q http://127.0.0.1:8769/recovery/sx -O /dev/null
	wget -q http://127.0.0.1:8769/recovery/dx -O /dev/null
	log "[${SIDE}] restarting mms..."
}

set_viewport()
{
	WIDTH=1280
	HEIGHT=720
	X_FACTOR=16
	Y_FACTOR=9

	NEW_WIDTH=$((${WIDTH} + ${HORIZ_OFFSET} * 2))
	NEW_HEIGHT=$((${NEW_WIDTH} * ${Y_FACTOR} / ${X_FACTOR}))

	scaleFactor=`echo "scale=3; ${NEW_WIDTH} / 1280" | bc`

	xOffset=`echo "-${HORIZ_OFFSET}" | bc`
	yOffset=`echo "scale=3; ${xOffset} * 9 / 16" | bc`

	log "NEW_WIDTH is ${NEW_WIDTH}"
	log "NEW_HEIGHT is ${NEW_HEIGHT}"
	log "xOffset is ${xOffset}"
	log "yOffset is ${yOffset}"

	if [ ! -f ${CONFIG_FILE} ]; then
		create_default_viewport
	fi

	(
		echo "${scaleFactor},0,${xOffset},0,${scaleFactor},${yOffset},0,0,1"
  	echo "${NEW_WIDTH} ${NEW_HEIGHT}"
	) > ${CONFIG_FILE}
}

check_params $@
set_viewport
