#!/bin/bash

export DISPLAY=:0

ROOT_PATH=${ROOT_PATH:-"/opt/qubicaamf/monitor/transform"}
VERBOSE=${VERBOSE:-0}

transform_sx=`cat ${ROOT_PATH}/SX`
transform_dx=`cat ${ROOT_PATH}/DX`

xrandr --output HDMI1 --transform "${transform_sx}" --output HDMI2 --pos 1280x0 --transform "${transform_dx}"
echo "xrandr --output HDMI1 --transform ${transform_sx} --output HDMI2 ---pos 1280x0 --transform ${transform_dx}"
